[package]
name = "ft_ality"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.7.0"
sdl2 = "0.36.0"
tailcall = "0.1.6"